### ISSUE TITLE
Move ITs to respective projects

### ISSUE THREAD

**Issue by tkrille** [osiam/connector4java-integration-tests#228]
There are too many system integrations tests. Most of the stuff here should be moved to the respective services as service integration tests. We should only maintain some crucial, happy path tests and tests that are only valid when testing against the complete system.

**Comment by dacrome** [comment]
Should I also copy the git history?

**Comment by wallner** [comment]
Yes, definitely!

**Comment by dacrome** [comment]
The [self-administration integration-tests were already moved](https://github.com/osiam/addon-self-administration/issues/162). The remaining tests are system integration tests for the connector and OSIAM. Just a few tests are not using the connector but a http client to test the OSIAM's REST endpoints directly. These tests should be moved to OSIAM.

Copy the git history and adjust OSIAM's pom was not a big deal. Bu the connector's and OSIAM's view on the SCIM classes (e.g. [User](https://github.com/osiam/osiam/blob/5b50a7cdcee6dd6469732c3d4998c6240181b3e7/src/main/java/org/osiam/resources/scim/User.java) and [Group](https://github.com/osiam/osiam/blob/5b50a7cdcee6dd6469732c3d4998c6240181b3e7/src/main/java/org/osiam/resources/scim/Group.java)) are not the same. The tests are failing because the connector's ObjectMapper do not know about the [jackson json filter](https://github.com/osiam/osiam/blob/5b50a7cdcee6dd6469732c3d4998c6240181b3e7/src/main/java/org/osiam/resources/scim/User.java#L67) which is used in OSIAM to filter attributes before sending the data back to the requester. But the tests need to use the connector's SCIM classes without the attribute filter.

There are several ways to deal with this problem:
1. Move OSIAM's SCIM classes in a different package
2. Move connector's SCIM classes in a different package
3. Connector's ObjectMapper should [not fail when the filter is not configured](https://github.com/osiam/osiam/blob/5b50a7cdcee6dd6469732c3d4998c6240181b3e7/src/main/java/org/osiam/configuration/JacksonConfig.java#L45)
4. Just move integration tests to OSIAM which are not using the connector

**Comment by dacrome** [comment]
'3. Is working, because connector's ObjectMapper is public static. I can set `OsiamConnector.objectMapper.setFilterProvider(new SimpleFilterProvider().setFailOnUnknownId(false));` in the static constructor of [AbstractIT](https://github.com/dacrome/osiam/blob/move-integration-tests/src/integrationtest/groovy/org/osiam/test/integration/AbstractIT.groovy#L66) and [AbstractIntegrationTestBase](https://github.com/dacrome/osiam/blob/move-integration-tests/src/integrationtest/java/org/osiam/client/AbstractIntegrationTestBase.java#L69)

[I pushed my changes to my fork](https://github.com/dacrome/osiam/tree/move-integration-tests).

**Comment by dacrome** [comment]
thanks for your issue, but this repository will be archived.
